// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Analytic { "30d": Record<string, bigint> | null, "90d": Record<string, bigint> | null, "365d": Record<string, bigint> | null, }