// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Dependencies { build_dependencies: Array<string> | null, dependencies: Array<string> | null, }