// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface File { cellar: string | null, url: string | null, sha256: string | null, }